apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dps-rook-ceph-example-block
  namespace: default
spec:
  resources:
    requests:
      storage: 5Gi
  storageClassName: "ceph-block"
  accessModes:
    - ReadWriteOnce
