cephClusterSpec:
  mon:
    count: 2
    allowMultiplePerNode: true
  mgr:
    count: 3
    allowMultiplePerNode: true
  storage:
    useAllNodes: false
    useAllDevices: false
    nodes:
      - name: "archlinux"
        devices: 
          - name: "/dev/nvme1n1p2"
            config:
              osdsPerDevice: "1"
toolbox:
  enabled: true
